[package]
name = "imag"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "build.rs"

[build-dependencies]
clap = ">=2.16.1"
version = "2.0"
libimagrt = { path = "../libimagrt" }
libimagentrytag = { path = "../libimagentrytag" }
libimagutil = { path = "../libimagutil" }

[profile.dev]
codegen-units = 2

[dependencies]
version = "2.0"
walkdir = "0.1"
crossbeam = "0.2"
clap = "2.*"
log = "0.3"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagerror]
path = "../libimagerror"

