[package]
name = "imag-root"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Personal information management (PIM) suite"
keywords = ["pim", "personal", "information", "management", "suite"]
readme        = "./README.md"
license       = "LGPL-2.1"

website = "http://imag-pim.org"
documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository = "https://github.com/matthiasbeyer/imag"

[profile.dev]
codegen-units = 2

[workspace]
members = [
    ".imag-documentation",
    "bin",
    "imag-link",
    "imag-notes",
    "imag-ref",
    "imag-store",
    "imag-tag",
    "imag-view",
    "libimagentryedit",
    "libimagentryfilter",
    "libimagentrylink",
    "libimagentrylist",
    "libimagentrymarkdown",
    "libimagentrytag",
    "libimagentryview",
    "libimagerror",
    "libimaginteraction",
    "libimagnotes",
    "libimagref",
    "libimagrt",
    "libimagruby",
    "libimagstore",
    "libimagstorestdhook",
    "libimagtimeui",
    "libimagutil",
]

[[bin]]
name = "imag-bin"
path = "bin/src/main.rs"

