[package]
name = "imag"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]
repository = ""
license = "GPLv2"
readme = "README.md"
description = "CLI PIM suite with nice API, so you can use an MUA, Editor, etc.  of your choice"

[dependencies]
log = "0.3.2"
regex = "0.1.41"
url = "0.2.37"
uuid = "0.1.18"

config = "0.1.2"

chrono = "0.2.16"

serde_json = "0.6.0"

clap = { version = "1.4.5", features = ["yaml"] }
rustty = "0.1.9"
term = "0.2.12"
term_grid = "0.1.2"

