[package]
name = "libimagrt"
version = "0.3.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = ">=2.17"
env_logger = "0.3"
toml = "^0.4"
log = "0.3"
xdg-basedir = "1.0"
itertools = "0.5"
tempfile = "2.1"
ansi_term = "0.9"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagutil]
path = "../libimagutil"

[dependencies.libimagerror]
path = "../libimagerror"

