[package]
name = "imag-habit"
version = "0.6.4"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-habit command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
chrono = "0.4"
clap = ">=2.17"
log = "0.3"
toml = "0.4"
toml-query = "0.6"
kairos = "0.1.0"

libimagerror       = { version = "0.6.4", path = "../../../lib/core/libimagerror" }
libimagstore       = { version = "0.6.4", path = "../../../lib/core/libimagstore" }
libimagrt          = { version = "0.6.4", path = "../../../lib/core/libimagrt" }
libimagentryedit   = { version = "0.6.4", path = "../../../lib/entry/libimagentryedit" }
libimagentrylist   = { version = "0.6.4", path = "../../../lib/entry/libimagentrylist" }
libimaginteraction = { version = "0.6.4", path = "../../../lib/etc/libimaginteraction" }
libimagutil        = { version = "0.6.4", path = "../../../lib/etc/libimagutil" }
libimagtimeui      = { version = "0.6.4", path = "../../../lib/etc/libimagtimeui" }
libimaghabit       = { version = "0.6.4", path = "../../../lib/domain/libimaghabit" }

