[package]
name = "imag-timetrack"
version = "0.4.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-tag command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = ">=2.17"
log = "0.3"
version = "2.0.1"
chrono = "0.4"
filters = "0.1"
itertools = "0.6"

libimagstore     = { version = "0.4.0", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.4.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.4.0", path = "../../../lib/core/libimagerror" }
libimagtimetrack = { version = "0.4.0", path = "../../../lib/domain/libimagtimetrack" }
