[package]
name = "libimagref"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
itertools = "0.4"
log = "0.3"
rust-crypto = "0.2"
semver = "0.2"
toml = "0.2.*"
version = "2.0.1"
walkdir = "0.1.5"

libimagentrylist = "0.2.0"
libimagerror     = "0.2.0"
libimagstore     = "0.2.0"
libimagutil      = "0.2.0"

