[package]
name = "libimagref"
version = "0.4.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
itertools = "0.5"
log = "0.3"
rust-crypto = "0.2"
semver = "0.5"
toml = "^0.4"
version = "2.0.1"
walkdir = "1.0.*"

libimagstore     = { version = "0.4.0", path = "../libimagstore" }
libimagerror     = { version = "0.4.0", path = "../libimagerror" }
libimagutil      = { version = "0.4.0", path = "../libimagutil" }
libimagentrylist = { version = "0.4.0", path = "../libimagentrylist" }
