[package]
name = "libimagstore"
version = "0.3.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
fs2 = "0.4"
glob = "0.2.11"
lazy_static = "0.2.*"
log = "0.3"
regex = "0.2"
semver = "0.5"
toml = "^0.4"
version = "2.0.1"
crossbeam = "0.2.*"
walkdir = "1.0.*"
itertools = "0.6.*"
is-match = "0.1"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

[dev-dependencies]
tempdir = "0.3.4"
env_logger = "0.3"

[features]
default = []
verify  = []

# Enable panic!()s if critical errors occur.
#
# # Howto
#
# To enable this, put
#
# ```toml
# [features]
# early-panic = [ "libimagstore/early-panic" ]
# ```
#
# In the crate depending on this library and compile your crate with
# `cargo build --features early-panic`. This way, the `libimagstore`
# implementation fails via `panic!()` instead of propagating errors which have
# to be printed somewhere to be visible.
#
# # WARNING
#
# The behaviour of the store implementation might be broken with this, resulting
# in partially written store entries and/or worse, so this is
#
#    _NOT INTENDED FOR PRODUCTION USE_!
#
early-panic=[]

# File system locking
#
# Enable this feature to enable file-system locking in the store.
fs-locking = []

