[package]
name = "libimagstore"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[profile.dev]
codegen-units = 2

[dependencies]
fs2 = "0.4"
glob = "0.2.11"
lazy_static = "0.2.*"
log = "0.3"
regex = "0.1"
semver = "0.5"
toml = "0.2.*"
version = "2.0.1"
crossbeam = "0.2.*"
walkdir = "1.0.*"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

[dev-dependencies]
tempdir = "0.3.4"
env_logger = "0.3"

[features]
default = []
verify  = []

