[package]
name = "imag"
version = "0.7.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "build.rs"

[build-dependencies]
clap = ">=2.16.1"
version = "2.0"
libimagrt = { path = "../../../lib/core/libimagrt" }
libimagentrytag = { path = "../../../lib/entry/libimagentrytag" }
libimagutil = { path = "../../../lib/etc/libimagutil" }

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
walkdir = "1"
log = "0.4.0"
toml = "0.4"
toml-query = "0.6"
is-match = "0.1"

libimagrt    = { version = "0.7.0", path = "../../../lib/core/libimagrt" }
libimagerror = { version = "0.7.0", path = "../../../lib/core/libimagerror" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["suggestions", "color", "wrap_help"]

