[package]
name = "imag-calendar"
version = "0.8.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-calendar command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "../../../build.rs"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log            = "0.4.0"
walkdir        = "2"
itertools      = "0.7"
prettytable-rs = "0.6"
chrono         = "0.4"
indicatif      = "0.9"

libimagcalendar  = { version = "0.8.0", path = "../../../lib/domain/libimagcalendar" }
libimagentryref  = { version = "0.8.0", path = "../../../lib/entry/libimagentryref" }
libimagerror     = { version = "0.8.0", path = "../../../lib/core/libimagerror" }
libimagrt        = { version = "0.8.0", path = "../../../lib/core/libimagrt" }
libimagstore     = { version = "0.8.0", path = "../../../lib/core/libimagstore" }
libimagtimeui    = { version = "0.8.0", path = "../../../lib/etc/libimagtimeui" }
libimagutil      = { version = "0.8.0", path = "../../../lib/etc/libimagutil" }

[dependencies.clap]
version = ">=2.29"
default-features = false
features = ["color", "suggestions"]

