[package]
name = "imag-notes"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
semver = "0.2.1"
clap = "2.*"
log = "0.3"
version = "2.0.1"
itertools = "0.4"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagnotes]
path = "../libimagnotes"

[dependencies.libimagentryedit]
path = "../libimagentryedit"

[dependencies.libimagentrytag]
path = "../libimagentrytag"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

