[package]
name = "imag-diary"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
chrono = "0.2"
version = "2.0"
clap = "2.*"
log = "0.3.5"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagdiary]
path = "../libimagdiary"

[dependencies.libimagentryedit]
path = "../libimagentryedit"

[dependencies.libimagentrylist]
path = "../libimagentrylist"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimaginteraction]
path = "../libimaginteraction"

[dependencies.libimagutil]
path = "../libimagutil"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagtimeui]
path = "../libimagtimeui"

