[package]
name = "imag-store"
version = "0.6.4"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-store command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
clap = ">=2.17"
log = "0.4.0"
toml = "0.4"
error-chain = "0.11"

libimagstore = { version = "0.6.4", path = "../../../lib/core/libimagstore", features = ["verify"] }
libimagrt    = { version = "0.6.4", path = "../../../lib/core/libimagrt" }
libimagerror = { version = "0.6.4", path = "../../../lib/core/libimagerror" }
libimagutil  = { version = "0.6.4", path = "../../../lib/etc/libimagutil" }

[features]
early-panic = [ "libimagstore/early-panic" ]

[dev-dependencies.libimagutil]
version          = "0.6.4"
path = "../../../lib/etc/libimagutil"
default-features = false
features         = ["testing"]

[dev-dependencies.libimagrt]
version          = "0.6.4"
path             = "../../../lib/core/libimagrt"
default-features = false
features         = ["testing"]

[dev-dependencies.toml-query]
version          = "0.4"

