# Contact template for imag-contact version 0.9.0
#
# This file is explicitely _not_ distributed under the terms of the original imag license, but
# public domain.
#
# Use this TOML formatted template to create a new contact.

[name]

# every entry may contain a string or a list of strings
# E.G.:
# first = "Foo"
# last = [ "bar", "bar", "a" ]
prefix     = "test"
first      = "test"
additional = "test"
last       = "test"
suffix     = "test"

[person]

# Birthday
# Format: YYYY-MM-DD
birthday = "2017-01-01"

# allowed types:
#   vcard 3.0: At least one of bbs, car, cell, fax, home, isdn, msg, modem,
#                              pager, pcs, pref, video, voice, work
#   vcard 4.0: At least one of home, work, pref, text, voice, fax, cell, video,
#                              pager, textphone
phone = [
    { "type" = "home", "number" = "0123 123456789" },
]

#
# Email addresses
#
email = [
    { "type" = "home", "addr" = "examle@examplemail.org" },
]

# post addresses
#
# allowed types:
#   vcard 3.0: At least one of dom, intl, home, parcel, postal, pref, work
#   vcard 4.0: At least one of home, pref, work
[[addresses]]
type     = "home"
box      = "testbox"
extended = "testextended"
street   = "teststreet"
code     = "testcode"
city     = "testcity"
region   = "testregion"
country  = "testcountry"

# Nickname
# "type" is optional
[[nickname]]
type = "work"
name = "boss"

[organisation]

# Organisation name
# May contain a string or a list of strings
name = "test"

# Organisation title and role
# May contain a string or a list of strings
title = "test"

# Role at organisation
# May contain a string or a list of strings
role  = "test"

[other]

# categories or tags
# May contain a string or a list of strings
categories = "test"

# Web pages
# May contain a string or a list of strings
webpage = "test"

# Notes
# May contain a string or a list of strings
note = "test"

