[package]
name = "libimagruby"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[lib]
crate-type = ["dylib"]

[dependencies]
ruru = "0.9"
lazy_static = "0.2"
log = "0.3"
env_logger = "0.3"
toml = "0.2"
uuid = { version = "0.3", features = ["v4"] }

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagstorestdhook]
path = "../libimagstorestdhook"

[dependencies.libimagutil]
path = "../libimagutil"

